### ISSUE TITLE
信息安全 2077-改系统时间

### ISSUE THREAD

**Issue by supermantou42** [ustclug/hackergame2019-writeups#4]
win10 1903，当时想直接改时间的时候发现只能设置到2049年😂

**Comment by Moreonenight** [comment]
在命令行里输命令(date)就可以随便调时间了。

**Comment by ustc-zzzz** [comment]
emmm，我是在 Linux 底下试的，回头抽空补充一下吧

**Comment by IsR00kie** [comment]
emmmm 我是伪造发包的

In [1]: headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36", "If-Unmodified-Since": "Fri, 01 Oct 2077 00:00:00 GMT"}                                       

In [2]: import requests                                                                                                                                                                                                                     

In [3]: requests.post("http://202.38.93.241:2077/flag.txt", headers=headers).text

**Comment by tomac4t** [comment]
再提供两种解法。

### 解法三 
```
$ curl http://202.38.93.241:2077/flag.txt -X POST -H "If-Unmodified-Since: Fri, 01 Oct 2077 00:00:00 GMT"
flag{Welc0me_to_competit1on_in_2077}
```
### 解法四
火狐用户在开发者工具网络选项卡中找到`http://202.38.93.241:2077/flag.txt`请求，点击`Edited and Resend`编辑请求头，点击`Send`发送请求，并在 Response 选项卡观察返回的结果：

![2019-10-23_15-18](https://user-images.githubusercontent.com/47532693/67367704-97b45700-f5a8-11e9-9711-9a8116d7e80c.png)
